name: deploy serverless scf
on: #监听的事件和分支配置
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy serverless scf
    runs-on: ubuntu-latest
    env:
      SERVERLESS_PLATFORM_VENDOR: tencent #serverless 境外默认为 aws，配置为腾讯
      TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }} #您的腾讯云账号 sercret ID，请在Settings-Secrets中配置
      TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }} #您的腾讯云账号 sercret key，请在Settings-Secrets中配置
    steps:
      - name: clone local repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      # 安装 serverless cli
      - name: install serverless cli
        run: sudo npm i serverless-tencent -g
      # 安装 typescript
      - name: install typescirpt cli
        run: sudo npm i typescript -g
      # 安装依赖
      - name: install dependency
        run: npm install
      # 编译 ts 代码
      - name: compile typescript
        run: tsc
      - name: deploy
        run: slt deploy
